name: 'Multiple Go Modules'
description: 'Run command in multiple repos'

inputs:
  pre:
    description: "Command(s) to run before `run`"
    required: false
  post:
    description: "Command(s) to run after `run`"
    required: false
  run:
    description: "Command(s) to run"
    required: true
  working-directory:
    description: "working directory"
    required: false

runs:
  using: "composite"
  steps:
    - shell: bash
      if: ${{ inputs.pre != "" }}
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.pre }}
    - shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        status=0
        dirs=$(find . \( -name vendor -o -name '[._].*' -o -name node_modules \) -prune -o -name go.mod -print | sed 's:/go.mod$::')
        len=$(echo "$dirs" | wc -l | tr -d ' ')
        for dir in $dirs; do
          pushd $dir > /dev/null
          if [[ $len > 1 ]]; then echo "::group::$dir"; fi
          ( 
            ${{ inputs.run }}
          )
          if [[ $len > 1 ]]; then echo "::endgroup::"; fi
          s=$?
          if [[ $s != 0 ]]; then status=$s; fi
          popd > /dev/null
        done
        exit $status
    - shell: bash
      if: ${{ inputs.post != "" }}
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.post }}
