name: 'Multiple Go Modules'
description: 'Run command in multiple repos'

inputs:
  run:
    description: "Command(s) to run"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        status=0
        for dir in $(find . \( -name vendor -o -name '[._].*' -o -name node_modules \) -prune -o -name go.mod -print | sed 's:/go.mod$::'); do
          echo "#=#=#=# $dir #=#=#=#"
          pushd $dir > /dev/null
          s=0
          ( 
            ${{ inputs.run }}
          ) || s=$?
          if [[ $s != 0 ]]; then status=$s; fi
          popd > /dev/null
          echo -e "\n\n"
        done
        exit $status
