name: 'Multiple Go Modules'
description: 'Run command in multiple repos'

inputs:
  run:
    description: "Command(s) to run"
    required: true
  working-directory:
    description: "working directory"
    required: false
  shell:
    description: "shell (options: 'bash' or 'msys2 {0}')"
    default: "bash"
    required: false

runs:
  using: "composite"
  steps:
    - name: create bash-or-msys2
      shell: bash
      run: |
        if [[ "${{ inputs.shell }}" == "msys2 {0}" ]]; then
          if [[ ! -f "D:/a/_temp/setup-msys2/bash-or-msys2.cmd" ]]; then
            powershell New-Item -ItemType SymbolicLink -Path "D:/a/_temp/setup-msys2/bash-or-msys2.cmd" -Target "D:/a/_temp/setup-msys2/msys2.cmd"
          fi
        elif [[ "${{ inputs.shell }}" == "bash" ]]; then
          sudo ln -sf $(which bash) /usr/local/bin/bash-or-msys2
        else
          echo "unknown shell: ${{ inputs.shell }}"
          exit 1
        fi
    - shell: bash-or-msys2 {0}
      working-directory: ${{ inputs.working-directory }}
      run: |
        status=0
        dirs=$(find . \( -name vendor -o -name '[._].*' -o -name node_modules \) -prune -o -name go.mod -print | sed 's:/go.mod$::')
        len=$(echo "$dirs" | wc -l | tr -d ' ')
        for dir in $dirs; do
          pushd $dir > /dev/null
          if [[ $len > 1 ]]; then echo "::group::$dir"; fi
          ( 
            ${{ inputs.run }}
          )
          if [[ $len > 1 ]]; then echo "::endgroup::"; fi
          s=$?
          if [[ $s != 0 ]]; then status=$s; fi
          popd > /dev/null
        done
        exit $status
